source 'https://rubygems.org'

# gem 'mysql2'
gem 'capybara'
gem 'chromedriver-helper', '1.2.0'
gem 'crb'
gem 'cucumber'
gem 'fig_newton'
gem 'geckodriver-helper'
gem 'headless'
gem 'httparty'
gem 'inifile'
gem 'pry'
gem 'rails_helper'
gem 'redis'
gem 'require_all'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'sequel'
gem 'site_prism'
gem 'syntax'
gem 'parallel_tests'
gem 'rake'
gem 'ffi'
